#!/bin/bash
#------------------------------------------------------------------------------
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: (c) 2026, ThinkElastic <Think@Elastic.com>
#------------------------------------------------------------------------------
#
# Lift the app mmap allocator out of kernel/syscall.c so the host harness
# exercises the SHIPPING implementation rather than a hand-copied paraphrase
# that can drift away from it silently.
#
# Boundaries are found by pattern, never by line number: syscall.c is edited
# often, and a line-number extract that quietly grabs the wrong region is
# worse than no test at all. Anything unmatched is a hard error.
#
#   ./extract.sh ../../syscall.c extracted.inc
set -euo pipefail

SRC="${1:?usage: extract.sh <syscall.c> <out.inc>}"
OUT="${2:?usage: extract.sh <syscall.c> <out.inc>}"

# Region 1: slot-table declarations through the end of sys_mmap2.
# Region 2: sys_munmap.
# Functions in this file close with a brace in column 0, which ends a region.
awk '
  /^#define MMAP_SLOTS/ { emit = 1 }
  emit == 1 { print }
  emit == 1 && /^static long sys_mmap2/ { seen = 1 }
  emit == 1 && seen == 1 && /^}/ { emit = 0; done = 1 }
  END { if (!done) { print "region 1 (MMAP_SLOTS..sys_mmap2) not found" > "/dev/stderr"; exit 1 } }
' "$SRC" > "$OUT.part1"

awk '
  /^static long sys_munmap/ { emit = 1 }
  emit == 1 { print }
  emit == 1 && /^}/ { emit = 0; done = 1 }
  END { if (!done) { print "region 2 (sys_munmap) not found" > "/dev/stderr"; exit 1 } }
' "$SRC" > "$OUT.part2"

{
  echo "/* GENERATED by extract.sh from kernel/syscall.c -- do not edit. */"
  cat "$OUT.part1"
  echo
  cat "$OUT.part2"
} > "$OUT"
rm -f "$OUT.part1" "$OUT.part2"

# Cheap self-check: everything the harness calls must have come across.
for sym in MMAP_SLOTS mmap_merge_free mmap_find_reusable sys_mmap2 sys_munmap; do
  grep -q "$sym" "$OUT" || { echo "extract.sh: '$sym' missing from $OUT" >&2; exit 1; }
done
echo "extract.sh: $(grep -c '' "$OUT") lines -> $OUT"
