#
# APF constraints
# Do not edit this file.
#
# Add your own constraints in the \core_constraints.sdc in the core directory, which will also be loaded.

create_clock -name clk_74a -period 13.468 [get_ports clk_74a]
create_clock -name clk_74b -period 13.468 [get_ports clk_74b]
create_clock -name bridge_spiclk -period 13.468 [get_ports bridge_spiclk]

# autogenerate PLL clock names for use down below
derive_pll_clocks


# io constraints go here
# 


# User constraints are loaded by ap_core.qsf
# (`set_global_assignment -name SDC_FILE core_constraints.sdc`).
# The original `read_sdc "core/core_constraints.sdc"` assumed a pre-flattening
# layout with a ./core subdirectory and triggered Critical Warning (332012)
# under the current tree layout.